[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[phases.setup]
nixPkgs = ["nodejs-18_x", "chromium"]

[phases.install]
cmd = "npm ci --only=production"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start"