[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm start"
restartPolicyType = "always"
healthcheckPath = "/api/bot/status"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
PORT = "5000"

[[services]]
name = "whatsapp-bot"